### PR TITLE
feat(ui): Add event name and time in dashboard

### LINKED ISSUE #1856: Add event name and time in dashboard
**Describe the chore**
Dashboard needs to display the event name and timing.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1856 

Screenshot for the change:
Add event name and time

### CODE REVIEW

**Comment by ShridharGoel** [comment]
@iamareebjamal Please check the screenshot.

**Comment by ShridharGoel** [comment]
@iamareebjamal Please see the screenshot and tell if it's fine.

**Comment by iamareebjamal** [comment]
User will have no idea what the switch is for. UI needs to improve

**Comment by ShridharGoel** [comment]
What about this?

Dashboard

**Comment by iamareebjamal** [comment]
Show event name instead of Event Dashboard

**Comment by ShridharGoel** [comment]
Event dashboard

**Comment by ShridharGoel** [comment]
@iamareebjamal Is this fine?

**Comment by iamareebjamal** [comment]
Add date in the subtitle of toolbar

**Comment by ShridharGoel** [comment]
@iamareebjamal Done

Event Dashboard

**Comment by iamareebjamal** [comment]
Decrease the subtitle size please. It's too large

**Comment by ShridharGoel** [comment]
Is this fine or should the size be reduced further?

Event Dashboard

**Pull request merged**
