### PR TITLE
feat: Add 'About The App' section

### LINKED ISSUE #1882: Add 'About the app' section
**Describe the feature you'd like**
Add 'About the app' section.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1882 

Screenshot for the change:

About The App

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Add OSS license section

**Comment by iamareebjamal** [comment]
What about F-Droid build

**Comment by iamareebjamal** [comment]
Change `OSS Licenses` to `3rd Party Libraries Used`

**Comment by ShridharGoel** [comment]
> What about F-Droid build

Updated, now `3rd Party Libraries Used` will show only in the Play Store build.

**Comment by ShridharGoel** [comment]
> Change `OSS Licenses` to `3rd Party Libraries Used`

Done.

**Comment by ShridharGoel** [comment]
> Huge duplication for not showing a single button

Updated.

**Pull request merged**
