### PR TITLE
GroovyRuntimeException resolved

### LINKED ISSUE #2212: GroovyRuntimeException on build
**Describe the bug**
Error at the time of build
**To Reproduce**
1. Clone project
2. Build project
3. Scroll down to 'build output'
4. See error `Caused by: groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'sourceDirectories' for task ':app:testFdroidDebugUnitTestCoverage' of type org.gradle.testing.jacoco.tasks.JacocoReport.`

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Pixel 2 |
|Android Version|  11.0  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by gargVader**
Fixes #2212 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 
- Deprecated methods were used. Updated taking reference from https://docs.gradle.org/current/userguide/upgrading_version_5.html#other_deprecated_behaviors_and_apis

- Gradle version and Gradle Plugin version updated

Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Build failing

**Comment by gargVader** [comment]
> Build failing

Can you post a screenshot of your error. Everything seems to be fine on my machine

**Comment by iamareebjamal** [comment]
Please share screenshot from your end as well, if it is showing everything is alright, then there is a bug in GitHub or CircleCI

image

**Comment by gargVader** [comment]
Is there anything else that I should post too? Sorry, its been just 2 months for me into android. I am still learning
Screenshot (10)

**Comment by iamareebjamal** [comment]
Post the area of GitHub I have posted where it is written that circle CI build is failing

**Comment by gargVader** [comment]
It is the same as yours. Any idea why that is happening?

**Comment by iamareebjamal** [comment]
Click on details

**Comment by gargVader** [comment]
[Circle CI's build output]( https://pastebin.com/hvH6b19T)
[My build output on local machine](https://pastebin.com/K1LjPf7j)

Its running fine on my machine

**Comment by iamareebjamal** [comment]
But we can't merge your machine, we need PR's build to be fixed. That's not how it works

**Comment by gargVader** [comment]
> But we can't merge your machine, we need PR's build to be fixed. That's not how it works

😂 Rofl! I am looking for errors

**Pull request closed without merging**
