### PR TITLE
feat: Added rating dialog

### LINKED ISSUE #2044: Adding a rating system
**Describe the feature you'd like**
Usually applications like Google Maps etc have a dialog which asks the users if they want to review the application. I would be nice to have it as most of the user don't bother to rate the application not because they don't want to but theywould have to go to the play store and open application page view then  review it.

**Screenshots**
Not really required

**Additional context**
This rating would give developers more options to read the rating and work on the issue

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by scixor**
Fixes #2044

## Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

## Changes: 
- added Rating Dialog from https://github.com/marcoscgdev/RateDialog which is very simple to install and execute
- added strings for display purposes , I didn't add chin ease version because unfortunately I don't know it😅

## Screenshots for the change:
Screenshot_20200121-164508

> Note: The apk file below shows every time you open the app for easy debug purposes using `RateDialog.show(this)` . it has been changed in the application

[ratingFeature.zip](https://github.com/fossasia/open-event-organizer-android/files/4090904/ratingFeature.zip)

### CODE REVIEW

**Comment by scixor** [comment]
the tests seem to fail from internal reason's in circleci .. The error occours in my other pr where nothing has really changed 😅 to cause this kind of thing
```
> Task :app:testPlayStoreDebugUnitTest
Picked up _JAVA_OPTIONS: -Xmx2048m -Dorg.gradle.daemon=false

failed to abort Gradle Worker Daemon 1
org.gradle.process.internal.ExecException: A problem occurred waiting for process 'Gradle Worker Daemon 1' to complete.
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:237)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:214)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:364)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at org.gradle.process.internal.shutdown.ShutdownHooks.removeShutdownHook(ShutdownHooks.java:33)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:204)
	at org.gradle.process.internal.DefaultExecHandle.aborted(DefaultExecHandle.java:360)
	at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:108)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:84)
	... 7 more

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by scixor** [comment]
@iamareebjamal @Orbiter Please review

**Review by jayasanka-sack — APPROVED** [review]

**Review by codedsun — CHANGES_REQUESTED** [review]
@Sid911 - An entire library import for just the functionality of rating? Why can't we simply create a layout and inflate that in an alert dialog?

**Comment by iamareebjamal** [comment]
We don't need it

**Comment by scixor** [comment]
@codedsun I actually thought of that but after reading up on https://developer.android.com/topic/performance/reduce-apk-size in this section
image

which is already enabled in the application.. there isn't actually much point because it already decreases any sort of overhead plus after downloaded from https://github.com/marcoscgdev/RateDialog/releases the entire project is 375 kb ... and by project I mean 
image

so the lib which we are including might have like 20kb-40kb overhead ... so I did do the research when I did this 😇


<blockquote><div>Android Developers</div><div><strong><a href="https://developer.android.com/topic/performance/reduce-apk-size">Reduce your app size  |  Android Developers</a></strong></div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/marcoscgdev/RateDialog">marcoscgdev/RateDialog</a></strong></div><div>An android library to display a rate dialog in an easy way. - marcoscgdev/RateDialog</div></blockquote>

**Comment by scixor** [comment]
also every major app by google amazon facebook has this feature _(and my every I mean you can go and search any application from those companies)_ ... its viable feature which allows users to rate the application which brings user feedback with it as not everyone can come to github and report an issue, and this implementation just asks for user's feedback once after 5 days😀 of installation, if the user says no, it doesn't harm anything.

**Comment by iamareebjamal** [comment]
We are providing a service for people to make their own Open Event system, not providing the app. So Google Play Rating means nothing for us

**Pull request closed without merging**
