### PR TITLE
fix: Fixed date-time issue while creating events

### LINKED ISSUE #1984: Automatic change of date/time to current time/date on changing either of the value while creating an event.
**Describe the bug**

While creating an event, when you select a date and then change the time, the date is changed to current date. Similarly, when you set time of an event and then change the date, the time sets to the current time.

**To Reproduce**

1. Go to create event activity
2. Click on start date and select tomorrow's date 
3. Now change the time
4. The date is reset to the original value
5. Now change the date and the time restores to the current value.
6. The process continues infinitely for both start and end time.

**Expected behavior**

There should be no change on date/time on changing other's value.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G4 Plus|
|Android Version|Oreo 8.1    |

**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by rishabh-997**
Fixes #1984 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes:
1. In the DatePicker custom view class, on selecting the date, the time was taken to be default zone time instead of the user-selected time, so I converted the date string passed into Date object to get the hour and minute and added it to final date instead of using the current time.
2. Similarly, in the TimePicker custom view class, on selecting the time, the date was taken to be default zone date instead of the user-selected date, so I converted the date string passed into Date object to get the year, month and day and added it to final date instead of using current date.

testing

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Add GIF and follow commit guidelines.

**Comment by ShridharGoel** [comment]
Fix the PR title and in the 'Changes' section mention how you solved the issue and what changes you have made instead of adding the links of files changed which can easily be seen in the 'Files changed' section.

**Comment by ShridharGoel** [comment]
Read this: https://chris.beams.io/posts/git-commit/

<blockquote><div><strong><a href="https://chris.beams.io/posts/git-commit/">How to Write a Git Commit Message</a></strong></div></blockquote>

**Comment by iamareebjamal** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/com/eventyay/organizer/ui/views/DatePicker.java  1
- app/src/main/java/com/eventyay/organizer/ui/views/TimePicker.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/open-event-orga-app/open-event-orga-app/pullRequest?prid=4591570&bid=15416279)

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
It's a workaround, not a fix. Also, remove all unrelated commits

**Comment by rishabh-997** [comment]
> It's a workaround, not a fix. Also, remove all unrelated commits



> It's a workaround, not a fix. Also, remove all unrelated commits

Working on removing those commits. Sir, since the same variable is being changed while picking date/time, and the previous code sets the current time to the date, therefore it needs to be updated from the previous date. Can you suggest any other alternative? @ShridharGoel @iamareebjamal

**Pull request closed without merging**
