### PR TITLE
fix: Action bar title when returning from legal fragment

### LINKED ISSUE #1923: Action bar title changes to 'false' on going back from Legal option in About Us
**Describe the bug**
Action bar title changes to 'false' on going back from Legal option in About Us section.

**Would you like to work on the issue?**
Open to all

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #1923 
Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 
Fixes the action bar title when returning from legal options in about fragment

Screenshots for the change:

### CODE REVIEW

**Comment by liveHarshit** [comment]
What? Simply Go to legal and press back. Why skipping till about up?

**Comment by codedsun** [comment]
@liveHarshit that means? didn't understand..

**Comment by liveHarshit** [comment]
> @liveHarshit that means? didn't understand..
> 
> I only back pressed after going to legal

GIF is not displaying now?

**Comment by codedsun** [comment]
@liveHarshit I dont' know what happened, let me upload that again
ezgif com-video-to-gif

**Comment by codedsun** [comment]
@liveHarshit any updates?

**Pull request merged**
