### PR TITLE
feat: Option to delete profile picture

### LINKED ISSUE #1836: Add option to delete profile image
**Describe the feature you'd like**
User should have the option to remove profile image.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1836 

GIF for the change:

Delete profile picture

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Updated.

**Comment by iamareebjamal** [comment]
Icon is too large. Add padding

**Comment by iamareebjamal** [comment]
The button should hide when there is no image

**Comment by ShridharGoel** [comment]
Updated.

**Pull request merged**
