### PR TITLE
[WIP] fix: Update profile picture in navigation drawer

### LINKED ISSUE #1860: Profile picture does not show in navigation drawer until app is reopened
**Describe the bug**
On updating profile picture, it does not show in the navigation drawer until the app is reopened.

**Would you like to work on the issue?**
Open to all.

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1860 

Changes:

Show updated profile picture in navigation drawer after image is updated.

### CODE REVIEW

**Comment by ShridharGoel** [comment]
@iamareebjamal Please check, it is fetching the updated image link in `onResume()` but the picture is not being updated in the navigation drawer.

**Comment by iamareebjamal** [comment]
Of course it isn't. loadOrganiser is not synchronous

**Comment by ShridharGoel** [comment]
How can it be made synchronous?

**Comment by iamareebjamal** [comment]
It can't

**Comment by iamareebjamal** [comment]
It's strange for me how you have worked on this project for months and you don't realize this

**Comment by ShridharGoel** [comment]
Yes I realize that but then how can this be done?

**Comment by iamareebjamal** [comment]
subscribe the single

**Pull request closed without merging**
