### PR TITLE
WIP feat: Stripe Integration 

### LINKED ISSUE #1327: Integrate Stripe Payments in app
### Feature Request

**Feature Description**

Integrate Payments with stripe for creating orders.
   
**Would you like to work on the issue?**

This is open for all and is meant to be handled after GSoC.

### PR DESCRIPTION
**Pull request by kush-mish**
Fixes #1327 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 

- Creates a button to redirect to the `authorize_url` endpoint. When the user clicks the button, it takes the user to the Stripe's website.
- After the successful form completion, it redirects the user back to the app, with the authorization code.
- Then the app provides this authorization code to make a POST request to the `access_token_url` endpoint to fetch the user’s Stripe credentials. 

Screenshots for the change:

### CODE REVIEW

**Comment by kush-mish** [comment]
@iamareebjamal help me with the lifecycle for the process. What changes are expected to be done in the process shown in the GIF?

**Comment by ShridharGoel** [comment]
@kush-mish Upon clicking 'Connect with stripe' why does the next screen again shows the same button?

**Comment by kush-mish** [comment]
@ShridharGoel Actually, for redirecting back to the app with the `callback_url`, we need to add intent-filter to an activity. And since I couldn't add it to the CreateEventActivity(as it would open the Create Event Activity for a new event and not the UpdateEventFragment), I had to create another activity to redirect to. This StripeLoginActivity finishes as the user redirects back to the app.
Can you suggest the other way around?

**Comment by ShridharGoel** [comment]
If there is no way around then we will need to have a better UI for that activity which can contain information regarding Stripe along with a 'Proceed' button instead of the current button.

**Comment by ShridharGoel** [comment]
We don't use Retrofit in this way in the project. Please implement it with RxJava.

**Pull request closed without merging**
